name = "angpow_ens_worker"
compatibility_date = "2024-09-20"
compatibility_flags = [ "nodejs_compat" ]
account_id = "33c9bad56490db21d8c0241b4cbb8028"

# [vars]

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
